package com.google.ads.interactivemedia.p038v3.internal;

/* renamed from: com.google.ads.interactivemedia.v3.internal.dv */
/* compiled from: IMASDK */
public enum C3948dv {
    activate,
    adBreakEnded,
    adBreakFetchError,
    adBreakReady,
    adBreakStarted,
    adBuffering,
    adCanPlay,
    adMetadata,
    adPeriodEnded,
    adPeriodStarted,
    adProgress,
    adsLoaded,
    allAdsCompleted,
    appBackgrounding,
    appForegrounding,
    appStateChanged,
    click,
    companionView,
    complete,
    contentComplete,
    contentPauseRequested,
    contentResumeRequested,
    contentTimeUpdate,
    csi,
    cuepointsChanged,
    destroy,
    discardAdBreak,
    displayCompanions,
    durationChange,
    end,
    error,
    firstquartile,
    focusUiElement,
    forwardCompatibleUnload,
    nativeRequest,
    nativeResponse,
    getViewability,
    hide,
    iconFallbackImageClosed,
    impression,
    init,
    initialized,
    load,
    loaded,
    loadStream,
    log,
    midpoint,
    mute,
    navigationRequested,
    omidReady,
    omidUnavailable,
    pause,
    play,
    registerFriendlyObstructions,
    replaceAdTagParameters,
    requestAds,
    requestNextAdBreak,
    requestStream,
    resizeAndPositionVideo,
    restoreSizeAndPositionVideo,
    resume,
    showVideo,
    skip,
    skippableStateChanged,
    start,
    startTracking,
    stopTracking,
    streamInitialized,
    thirdquartile,
    timedMetadata,
    timeupdate,
    unload,
    unmute,
    videoClicked,
    videoIconClicked,
    viewability,
    volumeChange,
    waiting;

    /* renamed from: a */
    public static C3948dv m16995a(String str) {
        return (C3948dv) Enum.valueOf(C3948dv.class, str);
    }
}
