package com.google.android.gms.internal.cast;

import com.google.android.exoplayer2.extractor.p039ts.TsExtractor;
import com.ironsource.mediationsdk.utils.IronSourceConstants;

/* renamed from: com.google.android.gms.internal.cast.a5 */
/* compiled from: com.google.android.gms:play-services-cast@@20.0.0 */
public enum C8435a5 implements C8736sc {
    EVENT_ACTION_UNKNOWN(0),
    DISCOVERED_CAST_DEVICE(1),
    MDNS_RESPONSE_PARSE_ERROR(2),
    MDNS_SUBTYPE_DISCOVERY_RESULT(3),
    ADAPTIVE_DISCOVERY_RESULT(4),
    SLOW_MDNS_RESPONSE(5),
    DEVICE_SCAN_STARTED(TsExtractor.TS_STREAM_TYPE_HDMV_DTS),
    DEVICE_SCAN_CRITERIA_CHANGED(131),
    DEVICE_SCAN_STOPPED(132),
    DEVICE_SCAN_PAUSED(133),
    DEVICE_SCAN_RESUMED(TsExtractor.TS_STREAM_TYPE_SPLICE_INFO),
    DEVICE_SCAN_PING(TsExtractor.TS_STREAM_TYPE_E_AC3),
    DEVICE_EXPIRED(136),
    PUBLISHED_DEVICES(137),
    NETWORK_CONNECTIVITY_CHANGED(190),
    DEVICE_FILTER_CONNECT_TO_DEVICE(10),
    DEVICE_FILTER_CONNECTION_FAILED(11),
    DEVICE_FILTER_CONNECTION_SUCCESS(12),
    DEVICE_FILTER_SENT_APP_AVAILABILITY_MESSAGE(13),
    DEVICE_FILTER_RECEIVED_APP_AVAILABILITY_MESSAGE(14),
    DEVICE_FILTER_SENT_STATUS_MESSAGE(15),
    DEVICE_FILTER_RECEIVED_STATUS_MESSAGE(16),
    DEVICE_FILTER_IGNORING_RECEIVED_MESSAGE(17),
    DEVICE_FILTER_FINISHED(18),
    DEVICE_FILTER_ERROR(19),
    DEVICE_FILTER_TIMED_OUT(20),
    DEVICE_CONTROLLER_CONNECT_TO_DEVICE(30),
    DEVICE_CONTROLLER_CONNECTION_FAILED(31),
    DEVICE_CONTROLLER_CONNECTION_SUCCESS(32),
    LAUNCH_APPLICATION(40),
    LAUNCH_APPLICATION_COMMAND(44),
    APPLICATION_CONNECTION_FAILED(41),
    APPLICATION_CONNECTION_SUCCESS(42),
    APPLICATION_DISCONNECTED(43),
    CAST_NEARBY_PROXIMITY_INFO_REQUEST(50),
    CAST_NEARBY_PROXIMITY_INFO_RESPONSE(51),
    CAST_NEARBY_START_AUDIO_TOKEN_PLAYBACK(52),
    CAST_NEARBY_STOP_AUDIO_TOKEN_PLAYBACK(53),
    DEVICE_CACHE_STATISTICS(60),
    REMOTE_DISPLAY_PLUGIN_SESSION_START(70),
    REMOTE_DISPLAY_PLUGIN_SESSION_END(71),
    REMOTE_DISPLAY_PLUGIN_ERROR(72),
    REMOTE_DISPLAY_PLUGIN_SESSION_START_FAILED(73),
    CONFIGURED_FLAGS_VALUE(160),
    REMOTE_CONTROL_NOTIFICATION_FAILED(170),
    REMOTE_CONTROL_NOTIFICATION_TRIGGERED(171),
    REMOTE_CONTROL_NOTIFICATION_CANCELED(183),
    REMOTE_CONTROL_NOTIFICATION_STOP(TsExtractor.TS_STREAM_TYPE_AC4),
    REMOTE_CONTROL_NOTIFICATION_MUTE(173),
    REMOTE_CONTROL_NOTIFICATION_UNMUTE(174),
    REMOTE_CONTROL_NOTIFICATION_PAUSE(175),
    REMOTE_CONTROL_NOTIFICATION_PLAY(176),
    REMOTE_CONTROL_NOTIFICATION_QUEUE_PREV(185),
    REMOTE_CONTROL_NOTIFICATION_QUEUE_NEXT(186),
    REMOTE_CONTROL_NOTIFICATION_CLICK_NOTIFICATION(184),
    REMOTE_CONTROL_NOTIFICATION_DISMISSED(177),
    REMOTE_CONTROL_NOTIFICATION_SETTING_TOGGLE_OFF(178),
    REMOTE_CONTROL_NOTIFICATION_SETTING_TOGGLE_ON(179),
    PLAY_SERVICES_NOTIFICATIONS_DISABLED(180),
    REMOTE_CONTROL_NOTIFICATION_SETTING_OPEN_HOME_APP(181),
    REMOTE_CONTROL_NOTIFICATION_SETTING_GET_HOME_APP(182),
    DISCOVERY_START(201),
    DISCOVERY_STOP(202),
    DISCOVERY_PING(203),
    GENERIC_MDNS_RECEIVED(204),
    SUBTYPE_MDNS_RECEIVED(205),
    MDNS_PARSE_ERROR(206),
    BLE_SIGNAL_RECEIVED(207),
    TCP_PROBING_RESULT(208),
    DEVICE_PUBLISHED(209),
    MDNS_SCANNER_FAILED_TO_START(210),
    BLE_SCANNER_FAILED_TO_START(211),
    MDNS_REQUEST_QUEUE_SIZE_ON_SERVICE_START(212),
    MDNS_REQUEST_SENT_COUNT_PERIODICAL(213),
    ERROR_PROBE_DEVICE_SCREEN_IS_OFF(214),
    ERROR_MULTICAST_NOT_RECEIVED(215),
    RECOVERED_FROM_ERROR_MULTICAST_NOT_RECEIVED(216),
    APP_SESSION_STARTING(220),
    APP_SESSION_RUNNING(221),
    APP_SESSION_PING(222),
    APP_SESSION_MEDIA_COMMAND(223),
    APP_SESSION_SUSPENDED(224),
    APP_SESSION_RESUMING(225),
    APP_SESSION_RESUMED(226),
    APP_SESSION_END(227),
    APP_SESSION_RUNNING_NETWORK_CHANGED(228),
    API_USAGE_IOS(241),
    API_USAGE_REPORT(242),
    GET_WIFI_PASSWORD_SUCCESS(IronSourceConstants.INTERSTITIAL_DAILY_CAPPED),
    GET_WIFI_PASSWORD_ERROR(251),
    PREACHE_ACTIVITY(260),
    KEY_EXCHANGE_REQUEST(261),
    ERROR_SOCKET_NO_DATA_CONSUMED_WHEN_READ(270),
    ERROR_SELECTOR_NOT_BLOCKING_WHEN_NO_SOCKET(271),
    ERROR_FAIL_TO_SHUTDOWN_SOCKET_OUTPUT(272),
    ERROR_REPORT(280),
    CAST_MESSAGE_STATS(290),
    LOCAL_NETWORK_PERMISSION_STATUS_CHANGED(300),
    LOCAL_NETWORK_PERMISSION_SETTING_BUTTON_TAPPED(301),
    LOCAL_NETWORK_PERMISSION_DISMISS_BUTTON_TAPPED(IronSourceConstants.OFFERWALL_AVAILABLE),
    LOCAL_NETWORK_PERMISSION_LEARN_MORE_BUTTON_TAPPED(303),
    CAST_BUTTON_TAPPED(304),
    REMOTE_CASTING_SESSION_SUMMARY(310),
    CLOUD_DISCOVERY_RESULT(311);
    

    /* renamed from: n1 */
    private static final C8751tc<C8435a5> f43236n1 = null;

    /* renamed from: b */
    private final int f43262b;

    static {
        f43236n1 = new C8835z4();
    }

    private C8435a5(int i) {
        this.f43262b = i;
    }

    public final String toString() {
        return "<" + C8435a5.class.getName() + '@' + Integer.toHexString(System.identityHashCode(this)) + " number=" + this.f43262b + " name=" + name() + '>';
    }

    public final int zza() {
        return this.f43262b;
    }
}
